behaviors:
  TargetAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024            
      buffer_size: 16384          
      learning_rate: 3.0e-4 
      beta: 0.012                   
      epsilon: 0.15               
      lambd: 0.93                 
      num_epoch: 3                
      learning_rate_schedule: linear   
      beta_schedule: constant          
    network_settings:
      normalize: true             
      hidden_units: 256           
      num_layers: 2               
    reward_signals:
      extrinsic:
        gamma: 0.995              
        strength: 1.0             
      curiosity:
        strength: 0.0005          
        gamma: 0.99
        encoding_size: 128
        learning_rate: 3.0e-4
    keep_checkpoints: 5           
    max_steps: 40000000            
    time_horizon: 128             
    summary_freq: 5000            
    checkpoint_interval: 100000   
    threaded: true                