behaviors:
  TargetAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 16384
      learning_rate: 2.5e-4
      beta: 0.01
      epsilon: 0.15
      lambd: 0.90
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
      curiosity:
        strength: 0.001
        gamma: 0.99
        encoding_size: 128
        learning_rate: 2.5e-4
    keep_checkpoints: 5
    max_steps: 5000000
    time_horizon: 128
    summary_freq: 10000
    checkpoint_interval: 50000
    threaded: true
